// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function GetConfigData(): $CancellablePromise<$models.AMMConfigData> {
    return $Call.ByID(3503291419).then(($result: any) => {
        return $$createType0($result);
    });
}

export function InitAMMConfig(): $CancellablePromise<void> {
    return $Call.ByID(482406696);
}

export function SaveConfigData(cd: $models.AMMConfigData): $CancellablePromise<void> {
    return $Call.ByID(1863444580, cd);
}

export function SelectAnnoModsFolder(): $CancellablePromise<string> {
    return $Call.ByID(4046502710);
}

// Private type creation functions
const $$createType0 = $models.AMMConfigData.createFrom;
