// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import * as AMMConfig from "./ammconfig.js";
export {
    AMMConfig
};

export {
    AMMConfigData
} from "./models.js";
