// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class AMMConfigData {
    "modfolder": string;
    "apikey": string;
    "apiendpoint": string;

    /** Creates a new AMMConfigData instance. */
    constructor($$source: Partial<AMMConfigData> = {}) {
        if (!("modfolder" in $$source)) {
            this["modfolder"] = "";
        }
        if (!("apikey" in $$source)) {
            this["apikey"] = "";
        }
        if (!("apiendpoint" in $$source)) {
            this["apiendpoint"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AMMConfigData instance from a string or object.
     */
    static createFrom($$source: any = {}): AMMConfigData {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AMMConfigData($$parsedSource as Partial<AMMConfigData>);
    }
}
