// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';
import {context} from '../models';

export function GetConfigData():Promise<config.AMMConfigData>;

export function InitAMMConfig(arg1:context.Context):Promise<void>;
