// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetConfigData() {
  return window['go']['config']['AMMConfig']['GetConfigData']();
}

export function InitAMMConfig(arg1) {
  return window['go']['config']['AMMConfig']['InitAMMConfig'](arg1);
}

export function SaveConfigData(arg1) {
  return window['go']['config']['AMMConfig']['SaveConfigData'](arg1);
}

export function SelectAnnoModsFolder() {
  return window['go']['config']['AMMConfig']['SelectAnnoModsFolder']();
}
